name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      deploy_message:
        description: "Provide a message for deployment"
        required: true
        default: "Deploying to production"

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      - name: Deploy to Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_GRASS_08255500F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"
          api_location: ""
          output_location: "build"
