name: Deploy PRs to Production

on:
  workflow_dispatch:
  inputs:
    pr_numbers:
      description: "Comma-separated PR numbers to deploy"
      required: true
      default: ""

jobs:
  deploy_production:
    runs-on: ubuntu-latest
    environment: prod
    strategy:
      matrix:
        pr: ${{ fromJson('[' + github.event.inputs.pr_numbers.replace(' ', '').split(',').map(x => `"${x}"`).join(',') + ']') }}

    steps:
      - name: Checkout PR ${{ matrix.pr }}
        uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ matrix.pr }}/merge
          submodules: true
          lfs: false

      - name: Deploy PR ${{ matrix.pr }} to Production
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_GRASS_08255500F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: "/"
          api_location: ""
          output_location: "build"
